#设置语言
language: node_js

#设置语言版本
node_js: stable

#安装hexo及插件
install:
  - npm install

#hexo操作
script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "grassnest"  #修改name
  - git config user.email "xiaobin517@gmail.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${Travis_CI}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - blog  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/grassnest/grassnest.github.io.git  #设置GH_REF，注意更改yourname
